Mac: Fix missing safe_browsing dependency on ntp_background_proto
Fixes the below build error with macOS official builds.

FAILED: obj/chrome/browser/safe_browsing/safe_browsing/settings_reset_prompt_model.o
In file included from ../../chrome/browser/safe_browsing/settings_reset_prompt/settings_reset_prompt_model.cc:5:
In file included from ../../chrome/browser/safe_browsing/settings_reset_prompt/settings_reset_prompt_model.h:19:
In file included from ../../chrome/browser/profile_resetter/profile_resetter.h:22:
In file included from ../../chrome/browser/search/instant_service.h:20:
In file included from ../../chrome/browser/search/background/ntp_background_service.h:15:
../../chrome/browser/search/background/ntp_background_data.h:10:10: fatal error: 'chrome/browser/search/background/ntp_background.pb.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.