Add missing //chrome/common:mojo_bindings dependency
Fixes the following error:

../../cef/libcef/common/service_manifests/
  cef_content_browser_overlay_manifest.cc(15,10): fatal error:
'chrome/common/conflicts/module_event_sink_win.mojom.h' file not found